settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: rpquiz
  path: ./bot/
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
  commands:
    install:
      status: false
    build:
      status: false
    run:
      status: true
