version: '3.2'

services:
  vault:
    image: "vault:0.10.4"
    cap_add:
    - IPC_LOCK
    ports: ["8200:8200"]
    volumes:
    #    - ./keys/vault:/vault/config
    - ./vault/file:/vault/file
    environment:
    - 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "listener": { "tcp": { "address": "0.0.0.0:8200", "tls_disable": 1 } }, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    command: server

  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://ECSC00A01760.epam.com:8080
    - CONCOURSE_ADD_LOCAL_USER=test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_WORKER_GARDEN_NETWORK
    - CONCOURSE_VAULT_URL=http://vault:8200
    - CONCOURSE_VAULT_TLS_INSECURE_SKIP_VERIFY=true
    #    - CONCOURSE_VAULT_AUTH_BACKEND=approle
    - CONCOURSE_VAULT_PATH_PREFIX=/concourse
    - CONCOURSE_VAULT_CLIENT_TOKEN=0c14d43a-3fda-157b-44b8-af097d5a40f0
