repo_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJJwIBAAKCAgEAnRSr4ojvYk6SgRCnK4l4+ZELGXi+hHdRFwfB0mJiUzkBOwFO
  oeTZrlnCcYR4z+CRcaYy/JIcqGWWFi+O8IHdeYJZmZW7PZbU9ItL1xmMMEdCf/Xe
  ADiO/11l51iPxVi/J89w9z3tpsDv32D1MGqpehXpcGRFPSBeMGXGyRCQuyG8DTFK
  AwPBaBc4r90tdO6RMCiVtigt6Ck+OGjsaSCgnUsXviHVTsRVnu0nJPue9z5RjYGZ
  veVSKsS+/Q97BtJaMnvPhrYlmk5zPFNfteOlKzSk7gvTd3DrcjKdO62qsI8qRXd8
  oEi6fZMSh41kOt+4vIkGfZndT5ZF8rUAef6Nm7i4LVhKvTxx9Hqf5Y+9mOMFG0ur
  WHLH7WfzU5MrZM+IAm7et0W9Z4cTaSar/dTt/dEvaL8bLzK6mF/gCVicRuKxDmXc
  SUJ77C8vsMsUoy1TQvk3gDuf15Y6PXboai0iMNx3CdA3B7RPIPPwPXr8ftz93vol
  r9nrysHCbk7xZizEonEJDceP0CUrFD3zAengCQ9hbPloi4Fl4lF2BU33QOv6Sl9U
  9O9BJ/ZIPlhL+QaUZ/fQ/LDvTPxttHA2utpPDpMGVwXlBvLhsIHClYiRymPVMePu
  l6Mi+GgktAVlXzXNhNuFUVD8gruwruFW4+ZHTC86BhkwChoNFgDJTMphcKkCAwEA
  AQKCAgB2SvzuioUMGXPG8o2SAeMyvoIHWqDPDTPqDhNuply5o7JDh0Z6MOelnz8J
  UePRWKLvXWQERNyEDIyshIA2qvXo7bsgKFxrk00oJEam5DxolyGDT9sxe2Zk9Scq
  w8zxp1W9W0ENUHvKGn4KUPAU2B5tLFcyJrDlyZxlAiBjhrAX3N3LaZT9FDTweJxe
  BEiZSJfaFpY4KaX4siaDQLDYspOCIOzuaHhE6yI3nwzdkwgx1aKA2Fq5YRsxzhyu
  YpwZlQwL/KVaI43J2M57XaY0Sg02rlyOUCWeS1FkHK3AJZbng8knq0YVRu/6ZWmM
  33PdymFKyj4zFE5QAzEGCD0logdtUeH/RfE5wv3nMw6L+hfQvIAczwMW0LK03so2
  cA1MZBKltKla2osejoVuXk9pkgnQMCwsj7NclgHz/pGSdPgggD2NHZdWSfS0j6BH
  3WOTpFJbLlUAoDw0wnD+Mre8P+bXSGJ52tcbXLU2Qg36fwxQEVi9krx3dL6GR0nu
  HqugLvnWNAJHQPBoCG6GmcprHY0551Tcn7W73j3moeiSiAMEW8bwwGihMWsWXpPQ
  JGyrSwdwAYHFu8FkibaBG24viNOZQj3bCbZlq+EPnSgxqGej8POWrlwkWaavnI1G
  cJYZAX4pyBKt8zpxBZQerlKbHa96EEiP1Bv1WUkawMfsX4+PoQKCAQEAzO5eBvAu
  3hh7SfLpIkFYpcV2xjN5MuyqogJVab3jsz+aK9b94FJOgRLQ5q7kYXlfjHz+PI5b
  wdRNkLBorvIvzg8B7V1E1swpuPgBkuFaRa63dP2NQBdzTqNeVEQ0YLGErOYHEFEY
  +/La1c3RCtRTPsTfMtqkyuh4imV9B8ELIPvXxjd9HsBW2Spm/iCcA2E++h+X07An
  n+iBoOWhjYXUOE27UrGIpDIrgXLsPT27lL+6DRHmR2jRHOeyJNa/JgldgoEnXW1I
  u1juJU3XZQeINqpwZiHO6ye72lkGNgYsqYP7qShlLtPJfxil020XwPANJykdTlYO
  U+W3TlZ6uXBPPQKCAQEAxDmtam+Aub8Yr5fMAj1b96e6mhJU+Z3MA465Punq9cI4
  Zk6HjKnYNVbPBrRTgcZf85yTLUP9Bf4Meru5PGw+MFTWj7CtqpGcKL1oiv+V7BU1
  paaKIDNfEYq7DlGuAR/KXi2gUwcwyxfM3qzfYIeId6h+lT+kIa+zfpm3deI8GOBT
  AOurgu/GBNV5U1x7apC38kL2rwIkLzPszWhv3ZYIXC7f6G+rRhEyadii/aQa0VSQ
  qEVSM0C/hDdZSpm9pt+cWTHoPC/AHSuFIeqWZzapqiqKNV06eJSO5YOLDCE5oA3Y
  9iEDIhWdAkPhPzQ5Qigjl+tlcXr1zXHDC7FcEHG93QKCAQBn5WmSRu7b9rl60kZT
  8aFJ2gTPk4UcxlPz8w7unzDzzYkSNNtdgRz/31Q9v+lVab2BclVKyjnG2SXB9037
  dBm8dGtbte+SnsuAVWwm1U15Co1EKNAV8E2rTrQiMLoFU7qaFbz7DsKF6af8wW37
  +Y2CwzkNhUALBzUlpTJwXfSQcl4Axl0O3CCr1Q2GRW4TYJgXIzFMR4CvV6dwtTrk
  jzb6nJ4d3JgT9sOLy4HtwoB5d4KR4cNH7OInr2fnuWALnq/j3Cri+Obo5LtH+mD7
  fYgXfu2hOf63xds9Zej6NsMp5hoOtsYlqYX8g7h+qk5iqNFiSzvqXULCUjJO6xUp
  MsFZAoIBAAPAao1fZmGmwq0QxOjCDZEVlt69PPysxKrIvsfyJvjd5sAl/jd1Q9n5
  N+oT5ojTpx/8PWAfLaZArjJmhmseUq4P4S5MHXXmZMrunCIUMuSZnzX0ki19bfLi
  6SKj8yS4W+EjFC6iM4+ee99CBN9OmBBZm1n1JokyV8cy3ywU0DtVhqC84MGXHf0X
  q8MpQH7QF4Q9PYQpEVIJtxxSQ9lDthM1HjjOccLcL0+QwcUBrzWTXVSqRqEOOtsn
  R8DCYbrgCZg2+Q61hwHHxDraxldg1yuWtp/AkY6eoIDI3A62T+i8ewpxpSKwsRjK
  /XJ86B9Yrx2HdaAOzsZHx4fgszbpRc0CggEAGhTEP/qXTkEYeLpO5SUdG4ZXXPko
  QpTNUE6omte+Ut6fuwh7+eglHYjl5EYXFACESl48gbcRO+6xl84VxUS4IbyV1RuF
  bP8smkPj8R7M36uZVuW90awJ1Ypy/F0gt3Gfenb/IILPxi/vlR2pmeew1tLEWCD2
  71lLivZcASkiYWh6PnfUu5vpVOhiL7t3LObs9Pg8gNGnMxVsxH6J0TiTZR+4JPlF
  3nEQJsMlDJf5xNDrYgjTbTRUj9nElJ88RLTY5Yoa7FdlDgbG0jrJaUZsaSITs46q
  AVAKlbbbfMu2ML+ECLlmrD3KGILfaP5ie+EU7G1j49f45/Y1n/b6ZDAFmg==
  -----END RSA PRIVATE KEY-----
docker_login: avarabyeu
docker_pass: bnAYwR-Hrw6Z4dJqsP3z