resources:
- name: rpquiz-git
  type: git
  source:
    uri: git@gitlab.com:avarabyeu/rpquiz.git
    branch: master
    private_key: ((repo_key))
- name: rpquiz-docker-image
  type: docker-image
  source:
    repository: registry.gitlab.com/avarabyeu/rpquiz
    username: ((docker_login))
    password: ((docker_pass))

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: rpquiz-git
    trigger: true
  - put: rpquiz-docker-image
    params:
      params: {save: true}
      build: rpquiz-git
      dockerfile: rpquiz-git/DockerfileProd