resources:
- name: rpquiz-git
  type: git
  source:
    uri: git@gitlab.com:avarabyeu/rpquiz.git
    branch: master
    private_key: ((repo_key))
- name: rpquiz-docker-image
  type: docker-image
  source:
    repository: registry.gitlab.com/avarabyeu/rpquiz
    username: ((docker_login))
    password: ((docker_pass))

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: rpquiz-git
    trigger: true
  - put: rpquiz-docker-image
    get_params: { skip_download: true }
    params:
      cache: true
      params: {save: true}
      build: rpquiz-git
      dockerfile: rpquiz-git/DockerfileProd

  # Second job: Retrieve application from S3 Bucket and Deploy to Docker Server
- name: Deploy
  plan:
  - get: rpquiz-docker-image
    trigger: true
    # Only if build job has passed
    passed: [build]
  - task: deploy-docker
    params:
      DOCKER_HOST: ((docker_host))
      DOCKER_LOGIN: ((docker_login))
      DOCKER_PASS: ((docker_pass))
    config:
      # Use a docker image with AWS eb-cli to init, create environment and deploy application
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker:dind
      inputs:
      - name: rpquiz-docker-image
      run:
        path: sh
        args:
        - -c
        - |
          docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASS} ${DOCKER_HOST}
          docker load -i ./rpquiz-docker-image/image
          docker images
