resources:
- name: rpquiz-git
  type: git
  source:
    uri: https://gitlab.com/avarabyeu/rpquiz.git
    branch: master

- name: rpquiz-docker-image
  type: docker-image
  source:
    repository: registry.gitlab.com/avarabyeu/rpquiz


jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: service-index
    trigger: true
  - put: service-ui-docker-image
  params:
    build: service-ui/
    dockerfile: DockerfileProd