resource_types:
- name: ssh
  type: docker-image
  source:
    repository: quay.io/avarabyeu/concourse-ssh-resource

resources:
- name: rpquiz-git
  type: git
  source:
    uri: git@gitlab.com:avarabyeu/rpquiz.git
    branch: master
    private_key: ((repo_key))

- name: rpquiz-docker-image
  type: docker-image
  source:
    repository: quay.io/avarabyeu/rpquiz
    username: ((docker_login))
    password: ((docker_pass))

- name: staging-server
  type: ssh
  source:
    host: ((deploy_host))
    user: ((deploy_host_user))
    password: ((deploy_host_password))

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: rpquiz-git
    trigger: true
  - put: rpquiz-docker-image
    get_params: { skip_download: true }
    params:
      cache: true
      params: {save: true}
      build: rpquiz-git
      dockerfile: rpquiz-git/DockerfileProd

  # Second job: Retrieve application from S3 Bucket and Deploy to Docker Server
- name: Deploy
  plan:
  - get: rpquiz-docker-image
    trigger: true
    # Only if build job has passed
    passed: [build]
  - put: staging-server
    params:
      interpreter: /bin/sh
      script: |
#        echo "<docker_pass>" | docker login -u "<docker_login>" quay.io/avarabyeu/rpquiz --password-stdin
        docker pull quay.io/avarabyeu/rpquiz
        docker rm -f rpquiz || true
        docker run -d -p 4200:4200 --restart=always --name rpquiz -e TG_TOKEN="<docker_pass>" quay.io/avarabyeu/rpquiz
      placeholders:
      - name: "<docker_login>"
        value: ((repo_key))
      - name: "<telegram_token>"
        value: ((telegram_token))
#      - name: "<docker_pass>"
#        value: ((docker_pass))
